services:
    # Data provider wrapper for retrieving data from the
    # video manager pro API
    data_providers.vmpro:
        class: MovingImage\DataProvider\VideoManagerPro
        arguments:
            - '@vmpro_api.client'